package com.sherlock.app.data.repository

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.sherlock.app.data.model.SearchResult
import java.io.File

class ExportRepository(private val context: Context) {

    fun exportToCsv(results: List<SearchResult>, username: String): Uri {
        val sb = StringBuilder()
        sb.appendLine("Site,URL,Status,Category,Response Time (ms)")
        for (r in results) {
            sb.appendLine("\"${r.siteName}\",\"${r.url}\",${if (r.exists) "Found" else "Not Found"},\"${r.category.displayName}\",${r.responseTimeMs}")
        }

        val file = File(context.cacheDir, "sherlock_${username}_${System.currentTimeMillis()}.csv")
        file.writeText(sb.toString())
        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    }

    fun exportToHtml(results: List<SearchResult>, username: String): Uri {
        val found = results.filter { it.exists }
        val sb = StringBuilder()
        sb.appendLine("""
            <!DOCTYPE html>
            <html dir="rtl" lang="he">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Sherlock Report - $username</title>
                <style>
                    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; padding: 20px; }
                    h1 { color: #58a6ff; } h2 { color: #8b949e; }
                    .card { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 16px; margin: 8px 0; }
                    .found { border-right: 4px solid #3fb950; }
                    a { color: #58a6ff; text-decoration: none; }
                    .stats { display: flex; gap: 16px; margin: 16px 0; }
                    .stat { background: #161b22; border-radius: 12px; padding: 16px; flex: 1; text-align: center; }
                    .stat-num { font-size: 2em; font-weight: bold; color: #58a6ff; }
                </style>
            </head>
            <body>
                <h1>🔍 Sherlock Report</h1>
                <h2>שם משתמש: $username</h2>
                <div class="stats">
                    <div class="stat"><div class="stat-num">${found.size}</div>נמצאו</div>
                    <div class="stat"><div class="stat-num">${results.size}</div>נבדקו</div>
                    <div class="stat"><div class="stat-num">${if (results.isNotEmpty()) (found.size * 100 / results.size) else 0}%</div>אחוז הצלחה</div>
                </div>
        """.trimIndent())

        val grouped = found.groupBy { it.category }
        for ((category, items) in grouped) {
            sb.appendLine("<h2>${category.hebrewName} (${items.size})</h2>")
            for (item in items) {
                sb.appendLine("""<div class="card found"><a href="${item.url}" target="_blank">${item.siteName}</a> - ${item.responseTimeMs}ms</div>""")
            }
        }

        sb.appendLine("</body></html>")

        val file = File(context.cacheDir, "sherlock_${username}_${System.currentTimeMillis()}.html")
        file.writeText(sb.toString())
        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    }

    fun shareResults(results: List<SearchResult>, username: String) {
        val found = results.filter { it.exists }
        val text = buildString {
            appendLine("🔍 Sherlock Report - @$username")
            appendLine("נמצאו ${found.size} מתוך ${results.size} אתרים")
            appendLine()
            for (r in found) {
                appendLine("✅ ${r.siteName}: ${r.url}")
            }
            appendLine()
            appendLine("Generated by Sherlock for Android")
        }

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, "Sherlock Report - $username")
        }
        context.startActivity(Intent.createChooser(intent, "שתף תוצאות").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
    }
}
