import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Box,Button,Card,CardContent,Chip,CircularProgress,Container,Divider,Drawer,List,ListItemButton,ListItemText,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Toolbar,Typography,Switch,FormControlLabel} from '@mui/material';
import {api} from './api'; import {useAuth} from './auth'; import {Approvals,Projects} from './engineering'; import type {Page,User} from './types';

const sections=['Dashboard','Users','Devices','AI usage','Quotas','Feature flags','Security events','Audit logs','System health','App versions','Subscriptions','Payments','Notifications','Engineering','Engineering projects','Engineering approvals'] as const;
type Section=typeof sections[number];
function Login(){const {signIn,loading}=useAuth();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setError('');try{await signIn(email,password)}catch(e){setError(e instanceof Error?e.message:'Login failed')}}return <Container maxWidth="sm"><Box component="form" onSubmit={submit} sx={{mt:12}}><Card><CardContent><Stack spacing={2}><Typography variant="h4">Admin sign in</Typography><TextField label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit" variant="contained" disabled={loading}>{loading?<CircularProgress size={22}/>:'Sign in'}</Button>{error&&<Typography color="error">{error}</Typography>}<Typography variant="caption">Tokens are kept in memory only and are cleared when this tab reloads.</Typography></Stack></CardContent></Card></Box></Container>}
function Users(){const [data,setData]=useState<Page<User>|null>(null);const [err,setErr]=useState('');useEffect(()=>{api<Page<User>>('/admin/users?page=1&page_size=50').then(setData).catch(e=>setErr(String(e)))},[]);return <Panel title="Users" err={err}>{data&&<Table size="small"><TableHead><TableRow><TableCell>Email</TableCell><TableCell>Role</TableCell><TableCell>Status</TableCell><TableCell>Created</TableCell></TableRow></TableHead><TableBody>{data.items.map(u=><TableRow key={u.id}><TableCell>{u.email}</TableCell><TableCell>{u.is_admin?'Admin':'User'}</TableCell><TableCell><Chip size="small" label={u.is_active?'Active':'Disabled'} color={u.is_active?'success':'default'}/></TableCell><TableCell>{new Date(u.created_at).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table>}</Panel>}
function JsonPanel({title,path}:{title:string;path:string}){const [data,setData]=useState<unknown>(null);const [err,setErr]=useState('');useEffect(()=>{api(path).then(setData).catch(e=>setErr(String(e)))},[path]);return <Panel title={title} err={err}><Box component="pre" sx={{whiteSpace:'pre-wrap',overflow:'auto',fontSize:13}}>{data?JSON.stringify(data,null,2):'Loading…'}</Box></Panel>}
function Flags(){const [key,setKey]=useState('new_dashboard');const [enabled,setEnabled]=useState(false);const [message,setMessage]=useState('');async function save(){try{await api('/admin/feature-flags',{method:'POST',body:JSON.stringify({key,enabled,rollout_percentage:enabled?100:0})});setMessage('Saved')}catch(e){setMessage(String(e))}}return <Panel title="Feature flags"><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField label="Flag key" value={key} onChange={e=>setKey(e.target.value)}/><FormControlLabel control={<Switch checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>} label="Enabled"/><Button variant="contained" onClick={save}>Save</Button></Stack>{message&&<Typography sx={{mt:2}}>{message}</Typography>}</Panel>}
function Dashboard(){return <Stack spacing={2}><JsonPanel title="System" path="/admin/system"/><JsonPanel title="AI usage (7 days)" path="/admin/ai/usage?days=7"/></Stack>}
function SystemPanel(){const [enabled,setEnabled]=useState(false);const [message,setMessage]=useState('Service is temporarily unavailable for maintenance');const [result,setResult]=useState('');async function apply(){try{await api('/admin/maintenance',{method:'POST',body:JSON.stringify({enabled,message})});setResult('Maintenance mode updated')}catch(e){setResult(String(e))}}return <Stack spacing={2}><JsonPanel title="System health" path="/admin/system"/><Panel title="Maintenance mode"><Stack spacing={2}><FormControlLabel control={<Switch checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>} label="Maintenance enabled"/><TextField label="Message" value={message} onChange={e=>setMessage(e.target.value)}/><Button variant="contained" onClick={apply}>Apply</Button>{result&&<Typography>{result}</Typography>}</Stack></Panel></Stack>}
function Panel({title,err,children}:{title:string;err?:string;children:ReactNode}){return <Card><CardContent><Typography variant="h5" gutterBottom>{title}</Typography>{err?<Typography color="error">{err}</Typography>:children}</CardContent></Card>}
function Content({section}:{section:Section}){switch(section){case'Users':return <Users/>;case'Dashboard':return <Dashboard/>;case'Feature flags':return <Flags/>;case'Devices':return <JsonPanel title="Devices" path="/admin/devices"/>;case'AI usage':return <JsonPanel title="AI usage" path="/admin/ai/usage?days=30"/>;case'Quotas':return <JsonPanel title="Quotas" path="/admin/quotas"/>;case'Security events':return <JsonPanel title="Security events" path="/admin/security-events"/>;case'Audit logs':return <JsonPanel title="Audit logs" path="/admin/audit-logs"/>;case'System health':return <SystemPanel/>;case'App versions':return <JsonPanel title="App versions" path="/admin/app-versions"/>;case'Subscriptions':return <JsonPanel title="Subscriptions" path="/admin/subscriptions"/>;case'Payments':return <JsonPanel title="Payments" path="/admin/payments"/>;case'Notifications':return <JsonPanel title="Notifications" path="/admin/notifications"/>;case'Engineering':return <JsonPanel title="Autonomous engineering" path="/admin/engineering/summary"/>;case'Engineering projects':return <Projects/>;case'Engineering approvals':return <Approvals/>;default:return <Panel title={section}><Typography>Module unavailable.</Typography></Panel>}}
export default function App(){const {user,signOut}=useAuth();const [section,setSection]=useState<Section>('Dashboard');if(!user)return <Login/>;return <Box sx={{display:'flex'}}><Drawer variant="permanent" sx={{width:240,'& .MuiDrawer-paper':{width:240,boxSizing:'border-box'}}}><Toolbar><Typography fontWeight={700}>AI Platform</Typography></Toolbar><Divider/><List>{sections.map(s=><ListItemButton key={s} selected={section===s} onClick={()=>setSection(s)}><ListItemText primary={s}/></ListItemButton>)}</List><Box sx={{mt:'auto',p:2}}><Typography variant="caption">{user.email}</Typography><Button fullWidth onClick={signOut}>Sign out</Button></Box></Drawer><Box component="main" sx={{flexGrow:1,p:3,minWidth:0}}><Toolbar/><Content section={section}/></Box></Box>}
